services:
    entriesdb:
        image: mongo:5.0.0
        container_name: entries-database
        ports:
            - 27017:27017
        volumes:
            - ./mongo:/data/db
# port mi pc 27017 : port imagen
# volumen carpeta ./mongo : carpeta en Mongo(default) /data/db
